In [1]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
import seaborn as sns
import string

In [98]:
class DataGenerator:
    def __init__(self, rows = 20, cols_float = 2, cols_int = 2, cols_string = 2, cols_words=3,
                 numrange = 12, strrange = 500, draw = False):
        self.rows = rows
        self.cols_float = cols_float
        self.cols_int = cols_int
        self.cols_string = cols_string
        self.cols_words = cols_words
        self.numrange = numrange 
        self.strrange = strrange
        self.wordsCount = 5
        self.draw = draw
        #https://github.com/dwyl/english-words
        self.words = pd.read_csv('words_alpha.txt', sep=" ", header=None)
                
    def generateData(self):
        df = pd.DataFrame()
        random.seed(1)
        
        for i in range(self.cols_float):
            col_name =  'float' + str(i)
            
            seed = random.randint(0,10000) 
            df[col_name] = self.lognuniform(use_int = False, seed = seed)
            if self.draw == True:
                self.plot_density(df[col_name])
                     
        for i in range(self.cols_int):
            col_name = 'int' + str(i)
            seed = random.randint(0,10000) 
            df[col_name] = self.lognuniform(use_int = True, seed = seed)
            if self.draw == True:
                self.plot_density(df[col_name])
        
        for i in range(self.cols_words):
            col_name = 'string' + str(i)
            random.seed(random.randint(0,self.strrange))
            df[col_name] = self.randomWords() #(N = n)
        return df
    
        for i in range(self.cols_string):
            col_name = 'string' + str(i)
            random.seed(random.randint(0,self.strrange))
            #n = random.randint(0,self.strrange) 
            df[col_name] = self.randomString() #(N = n)
                 
    def lognuniform(self, base=np.e, use_int = True, seed = 0):
        np.random.seed(seed) 
        # Note: you can not use random.seed here since the np.random.uniform needs np.random.seed not random.seed.
        multiplier = np.random.choice([-1,1], size= self.rows)
        # -5 is used since we done want most of the value to be less than base
        exponentials = np.random.uniform(low = -5, high = self.numrange, size = self.rows)
        #data = np.power(base, np.random.uniform(low = -self.numrange, high = self.numrange, size = self.rows))
        data = np.power(base, exponentials)  * multiplier
        if (use_int == True):
            return data.astype(int)
        if (use_int == False):
            return data
        
    def randomString(self):
        mylist = []
        # Options are Uppercase letters, lowercase letters, spaces (*10)
        options = (string.ascii_letters + string.digits + string.punctuation + ' '*10)
        for i in range(self.rows):
            mystring = ''.join(random.choice(options) for i in range(random.randint(0,self.strrange)))
            mylist.append(mystring)
        return mylist

    def randomWords(self):
        mylist = []
        for i in range(self.rows):
            mystring = (' '.join(words.iat[random.randint(0,words.shape[0]),0] for i in range(random.randint(1,self.wordsCount)))).strip()
            mylist.append(mystring)
        return mylist
    
    def plot_density(self, col):
        count, bins, ignored = plt.hist(col, 15, density=True)
        plt.plot(bins, np.ones_like(bins), linewidth=2, color='r')
        plt.show()

In [99]:
datagen = DataGenerator(rows = 10000, cols_float = 20, cols_int = 20, cols_string = 20, cols_words=10)
df = datagen.generateData()
df.head()

,float0,float1,float2,float3,float4,float5,float6,float7,float8,float9,...,string0,string1,string2,string3,string4,string5,string6,string7,string8,string9
0,-498.746078,-0.008146,-16.452716,-353.806348,469.987818,14.839433,5612.103446,2115.507049,-934.248873,-39.411989,...,enhaemospore tendable rhynchophore cocillana sit,boo koppite watermen bluetick,mimming brothels,nitrogens,bushel,slumps hamstrung cartomancies,inessentiality teutonize antioxygenator toras ...,defailment clodpoles rissoidae,deg,echo sinoatrial fjorded langoon
1,0.032795,-0.047239,1.047444,296.889028,-251.950123,-54462.543116,-0.400589,-0.008071,9782.890331,3194.907548,...,sansi screenless synkinesis,oscar,intromittent ambulatorium steeped uncommunicat...,triggerfishes unfrocks ganancial ecclesial gar...,interestless gastrostege extrapleural,pulsidge plucker osteologies overtrust sexdigi...,heartquake azurmalachite,inhabitable,intrapsychically sulphinic,laparohepatotomy waxily anthrohopobiological
2,-28.482447,0.020538,-13447.448961,-0.207823,1093.821957,224.923158,1.825916,-391.462685,0.266313,-831.913003,...,precariously demiowl stasidia chondrin,patellae dafter scabrities unsalt,protestive,preabdomen creatophagous,benignities lepidopterist,inact phonier feoffor,natator uncage cotemporaries bullpup,landdrost birthstool soddiest syntonize,prestandard obstructed dodipole aboves,millimetric mirifical bimonthlies omophagia
3,2.026330,-270.894238,0.049570,-0.011564,25.542848,-12.719610,11375.286658,-105975.341183,2.914488,6309.295856,...,crucifers,unlowered contoured libyans,inpoured hyoids unimplicated unbinding rollick...,transversary,tropidine solitudinizing girgashite telegonies...,cubanite auletic guava titmal,adjacency royalisation goaves annihilator,karaburan lowlily ski,glossa hydrophyll pellucidity scandalmongering...,lingwort disembarking louk tropism
4,82.220440,-18320.395341,13525.403633,8136.053815,-141.149878,-26.778189,656.748882,2.789385,108.203967,-21442.403475,...,roestone celotomies luges yatigan,cytogenetical deportability grabbots nonestima...,unidolised patterist maravedis,disfranchise guttide bootlicker phytohemagglut...,garfish subcreek,noncomplying,dextroglucose,luminologist,nightclothes hemipinnate,recruitee

In [94]:
datagen = DataGenerator()
df = datagen.generateData()
df.head()
df.to_csv('data.csv')

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 50 columns):
float0     10000 non-null float64
float1     10000 non-null float64
float2     10000 non-null float64
float3     10000 non-null float64
float4     10000 non-null float64
float5     10000 non-null float64
float6     10000 non-null float64
float7     10000 non-null float64
float8     10000 non-null float64
float9     10000 non-null float64
float10    10000 non-null float64
float11    10000 non-null float64
float12    10000 non-null float64
float13    10000 non-null float64
float14    10000 non-null float64
float15    10000 non-null float64
float16    10000 non-null float64
float17    10000 non-null float64
float18    10000 non-null float64
float19    10000 non-null float64
int0       10000 non-null int32
int1       10000 non-null int32
int2       10000 non-null int32
int3       10000 non-null int32
int4       10000 non-null int32
int5       10000 non-null int32
int6       10000 non-null int32
int7       10000 non-null int32
int8       10000 non-null int32
int9       10000 non-null int32
int10      10000 non-null int32
int11      10000 non-null int32
int12      10000 non-null int32
int13      10000 non-null int32
int14      10000 non-null int32
int15      10000 non-null int32
int16      10000 non-null int32
int17      10000 non-null int32
int18      10000 non-null int32
int19      10000 non-null int32
string0    10000 non-null object
string1    10000 non-null object
string2    10000 non-null object
string3    10000 non-null object
string4    10000 non-null object
string5    10000 non-null object
string6    10000 non-null object
string7    10000 non-null object
string8    10000 non-null object
string9    10000 non-null object
dtypes: float64(20), int32(20), object(10)
memory usage: 3.1+ MB

In [101]:
## Lets now look at the total memory consumed by the pandas dataframe in memory 
for dtype in ['float','int','object']:
    selected_dtype = df.select_dtypes(include=[dtype])
    mean_usage = selected_dtype.memory_usage(deep=True).mean() 
    total_usage = selected_dtype.memory_usage(deep=True).sum()
    print("Average memory usage for {} columns: {:03.2f} KB".format(dtype,mean_usage))
    print("Total memory usage for {} columns: {:03.2f} KB".format(dtype,total_usage))

Average memory usage for float columns: 76194.29 KB
Total memory usage for float columns: 1600080.00 KB
Average memory usage for int columns: 38099.05 KB
Total memory usage for int columns: 800080.00 KB
Average memory usage for object columns: 793406.18 KB
Total memory usage for object columns: 8727468.00 KB

In [103]:
df.to_csv("data_rand.csv", index=False)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

   0
0  a

In [78]:
words.iat[random.randint(0,words.shape[0]),0]

mystring = (' '.join(words.iat[random.randint(0,words.shape[0]),0] for i in range(random.randint(0,5)))).strip()
print(mystring)

prees anticholinergic lowness favorers marooning

In [74]:
 mylist = []
        # Options are Uppercase letters, lowercase letters, spaces (*10)
        options =  random.randint(0,words.length()) 
        for i in range(self.rows):
            mystring = (' '.join(words.iat[random.randint(0,words.shape[0]),0] for i in range(random.randint(0,self.wordsCount)))).strip()
            mylist.append(mystring)
        return mylist

IndentationError: unexpected indent (<ipython-input-74-164f73a2b7ea>, line 3)